FROM node:20-alpine AS build
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG VITE_ROUTER_URL=""
ENV VITE_ROUTER_URL=$VITE_ROUTER_URL
ARG VITE_COGNITO_USER_POOL_ID=""
ENV VITE_COGNITO_USER_POOL_ID=$VITE_COGNITO_USER_POOL_ID
ARG VITE_COGNITO_CLIENT_ID=""
ENV VITE_COGNITO_CLIENT_ID=$VITE_COGNITO_CLIENT_ID
ARG VITE_ENABLE_AUTH="false"
ENV VITE_ENABLE_AUTH=$VITE_ENABLE_AUTH
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
